<?php
/**
 * AccessKeysApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Cloudinary\Provisioning
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloudinary Provisioning API
 *
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise).
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@cloudinary.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cloudinary\Provisioning\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Cloudinary\Provisioning\ApiException;
use Cloudinary\Provisioning\Configuration;
use Cloudinary\Provisioning\HeaderSelector;
use Cloudinary\Provisioning\ObjectSerializer;

/**
 * AccessKeysApi Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary\Provisioning
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccessKeysApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation generateAccessKey
     *
     * Generate an access key
     *
     * @param  string $sub_account_id sub_account_id (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyRequest $access_key_request Access key details (optional)
     *
     * @throws \Cloudinary\Provisioning\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Provisioning\Model\AccessKeyResponse
     */
    public function generateAccessKey($sub_account_id, $access_key_request = null)
    {
        list($response) = $this->generateAccessKeyWithHttpInfo($sub_account_id, $access_key_request);
        return $response;
    }

    /**
     * Operation generateAccessKeyWithHttpInfo
     *
     * Generate an access key
     *
     * @param  string $sub_account_id (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyRequest $access_key_request Access key details (optional)
     *
     * @throws \Cloudinary\Provisioning\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Provisioning\Model\AccessKeyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function generateAccessKeyWithHttpInfo($sub_account_id, $access_key_request = null)
    {
        $request = $this->generateAccessKeyRequest($sub_account_id, $access_key_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Cloudinary\Provisioning\Model\AccessKeyResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Cloudinary\Provisioning\Model\AccessKeyResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Provisioning\Model\AccessKeyResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Provisioning\Model\AccessKeyResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Provisioning\Model\AccessKeyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation generateAccessKeyAsync
     *
     * Generate an access key
     *
     * @param  string $sub_account_id (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyRequest $access_key_request Access key details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function generateAccessKeyAsync($sub_account_id, $access_key_request = null)
    {
        return $this->generateAccessKeyAsyncWithHttpInfo($sub_account_id, $access_key_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation generateAccessKeyAsyncWithHttpInfo
     *
     * Generate an access key
     *
     * @param  string $sub_account_id (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyRequest $access_key_request Access key details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function generateAccessKeyAsyncWithHttpInfo($sub_account_id, $access_key_request = null)
    {
        $returnType = '\Cloudinary\Provisioning\Model\AccessKeyResponse';
        $request = $this->generateAccessKeyRequest($sub_account_id, $access_key_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'generateAccessKey'
     *
     * @param  string $sub_account_id (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyRequest $access_key_request Access key details (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function generateAccessKeyRequest($sub_account_id, $access_key_request = null)
    {
        // verify the required parameter 'sub_account_id' is set
        if ($sub_account_id === null || (is_array($sub_account_id) && count($sub_account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sub_account_id when calling generateAccessKey'
            );
        }

        $resourcePath = '/sub_accounts/{sub_account_id}/access_keys';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($sub_account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sub_account_id' . '}',
                ObjectSerializer::toPathValue($sub_account_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($access_key_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($access_key_request));
            } else {
                $httpBody = $access_key_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAccessKeys
     *
     * Get access keys
     *
     * @param  string $sub_account_id sub_account_id (required)
     * @param  int $page_size How many entries to display on each page. (optional)
     * @param  int $page Which page to return (maximum pages 100). Default All pages are returned. (optional)
     * @param  string $sort_by Which response parameter to sort by. Possible values api_key, created_at, name, enabled. (optional)
     * @param  string $sort_order Control the order of returned keys. Possible values desc (default), asc. (optional)
     *
     * @throws \Cloudinary\Provisioning\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Provisioning\Model\AccessKeysResponse
     */
    public function getAccessKeys($sub_account_id, $page_size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        list($response) = $this->getAccessKeysWithHttpInfo($sub_account_id, $page_size, $page, $sort_by, $sort_order);
        return $response;
    }

    /**
     * Operation getAccessKeysWithHttpInfo
     *
     * Get access keys
     *
     * @param  string $sub_account_id (required)
     * @param  int $page_size How many entries to display on each page. (optional)
     * @param  int $page Which page to return (maximum pages 100). Default All pages are returned. (optional)
     * @param  string $sort_by Which response parameter to sort by. Possible values api_key, created_at, name, enabled. (optional)
     * @param  string $sort_order Control the order of returned keys. Possible values desc (default), asc. (optional)
     *
     * @throws \Cloudinary\Provisioning\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Provisioning\Model\AccessKeysResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAccessKeysWithHttpInfo($sub_account_id, $page_size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        $request = $this->getAccessKeysRequest($sub_account_id, $page_size, $page, $sort_by, $sort_order);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Cloudinary\Provisioning\Model\AccessKeysResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Cloudinary\Provisioning\Model\AccessKeysResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Provisioning\Model\AccessKeysResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Provisioning\Model\AccessKeysResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Provisioning\Model\AccessKeysResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAccessKeysAsync
     *
     * Get access keys
     *
     * @param  string $sub_account_id (required)
     * @param  int $page_size How many entries to display on each page. (optional)
     * @param  int $page Which page to return (maximum pages 100). Default All pages are returned. (optional)
     * @param  string $sort_by Which response parameter to sort by. Possible values api_key, created_at, name, enabled. (optional)
     * @param  string $sort_order Control the order of returned keys. Possible values desc (default), asc. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccessKeysAsync($sub_account_id, $page_size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        return $this->getAccessKeysAsyncWithHttpInfo($sub_account_id, $page_size, $page, $sort_by, $sort_order)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAccessKeysAsyncWithHttpInfo
     *
     * Get access keys
     *
     * @param  string $sub_account_id (required)
     * @param  int $page_size How many entries to display on each page. (optional)
     * @param  int $page Which page to return (maximum pages 100). Default All pages are returned. (optional)
     * @param  string $sort_by Which response parameter to sort by. Possible values api_key, created_at, name, enabled. (optional)
     * @param  string $sort_order Control the order of returned keys. Possible values desc (default), asc. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAccessKeysAsyncWithHttpInfo($sub_account_id, $page_size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        $returnType = '\Cloudinary\Provisioning\Model\AccessKeysResponse';
        $request = $this->getAccessKeysRequest($sub_account_id, $page_size, $page, $sort_by, $sort_order);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAccessKeys'
     *
     * @param  string $sub_account_id (required)
     * @param  int $page_size How many entries to display on each page. (optional)
     * @param  int $page Which page to return (maximum pages 100). Default All pages are returned. (optional)
     * @param  string $sort_by Which response parameter to sort by. Possible values api_key, created_at, name, enabled. (optional)
     * @param  string $sort_order Control the order of returned keys. Possible values desc (default), asc. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAccessKeysRequest($sub_account_id, $page_size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        // verify the required parameter 'sub_account_id' is set
        if ($sub_account_id === null || (is_array($sub_account_id) && count($sub_account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sub_account_id when calling getAccessKeys'
            );
        }

        $resourcePath = '/sub_accounts/{sub_account_id}/access_keys';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_order,
            'sort_order', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($sub_account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sub_account_id' . '}',
                ObjectSerializer::toPathValue($sub_account_id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateAccessKey
     *
     * Update an access key
     *
     * @param  string $sub_account_id sub_account_id (required)
     * @param  string $key key (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyUpdateRequest $access_key_update_request Access key details for update (optional)
     *
     * @throws \Cloudinary\Provisioning\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Cloudinary\Provisioning\Model\AccessKeyResponse
     */
    public function updateAccessKey($sub_account_id, $key, $access_key_update_request = null)
    {
        list($response) = $this->updateAccessKeyWithHttpInfo($sub_account_id, $key, $access_key_update_request);
        return $response;
    }

    /**
     * Operation updateAccessKeyWithHttpInfo
     *
     * Update an access key
     *
     * @param  string $sub_account_id (required)
     * @param  string $key (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyUpdateRequest $access_key_update_request Access key details for update (optional)
     *
     * @throws \Cloudinary\Provisioning\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Cloudinary\Provisioning\Model\AccessKeyResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateAccessKeyWithHttpInfo($sub_account_id, $key, $access_key_update_request = null)
    {
        $request = $this->updateAccessKeyRequest($sub_account_id, $key, $access_key_update_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Cloudinary\Provisioning\Model\AccessKeyResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Cloudinary\Provisioning\Model\AccessKeyResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Cloudinary\Provisioning\Model\AccessKeyResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Cloudinary\Provisioning\Model\AccessKeyResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Cloudinary\Provisioning\Model\AccessKeyResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateAccessKeyAsync
     *
     * Update an access key
     *
     * @param  string $sub_account_id (required)
     * @param  string $key (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyUpdateRequest $access_key_update_request Access key details for update (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAccessKeyAsync($sub_account_id, $key, $access_key_update_request = null)
    {
        return $this->updateAccessKeyAsyncWithHttpInfo($sub_account_id, $key, $access_key_update_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAccessKeyAsyncWithHttpInfo
     *
     * Update an access key
     *
     * @param  string $sub_account_id (required)
     * @param  string $key (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyUpdateRequest $access_key_update_request Access key details for update (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAccessKeyAsyncWithHttpInfo($sub_account_id, $key, $access_key_update_request = null)
    {
        $returnType = '\Cloudinary\Provisioning\Model\AccessKeyResponse';
        $request = $this->updateAccessKeyRequest($sub_account_id, $key, $access_key_update_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateAccessKey'
     *
     * @param  string $sub_account_id (required)
     * @param  string $key (required)
     * @param  \Cloudinary\Provisioning\Model\AccessKeyUpdateRequest $access_key_update_request Access key details for update (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateAccessKeyRequest($sub_account_id, $key, $access_key_update_request = null)
    {
        // verify the required parameter 'sub_account_id' is set
        if ($sub_account_id === null || (is_array($sub_account_id) && count($sub_account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sub_account_id when calling updateAccessKey'
            );
        }
        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling updateAccessKey'
            );
        }

        $resourcePath = '/sub_accounts/{sub_account_id}/access_keys/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($sub_account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sub_account_id' . '}',
                ObjectSerializer::toPathValue($sub_account_id),
                $resourcePath
            );
        }
        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($access_key_update_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($access_key_update_request));
            } else {
                $httpBody = $access_key_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
