<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Errors;

use Cloudinary\Account\Provisioning\Models\Components;
use Cloudinary\Account\Provisioning\Utils;
/** ErrorResponse - Bad request. */
class ErrorResponse
{
    /**
     *
     * @var ?\Cloudinary\Account\Provisioning\Models\Components\Error $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Cloudinary\Account\Provisioning\Models\Components\Error|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Components\Error $error = null;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  ?\Cloudinary\Account\Provisioning\Models\Components\Error  $error
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(?Components\Error $error = null, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->error = $error;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): ErrorResponseThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ErrorResponseThrowable($message, (int) $code, $this);
    }
}