<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Errors;

class PermissionsErrorResponseThrowable extends \RuntimeException
{
    public PermissionsErrorResponse $container;

    public function __construct(string $message, int $statusCode, PermissionsErrorResponse $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}