workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Cloudinary-Provisioning-OAS:
        inputs:
            - location: https://cloudinary.github.io/api-schemas/provisioning/schema.yml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: https://cloudinary.github.io/api-schemas/overlays/security-scheme-account-overlay.yaml
            - location: https://cloudinary.github.io/api-schemas/permissions/overlays/additional-properties-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/cloudinary/cloudinary/cloudinary-provisioning
targets:
    cloudinary:
        target: php
        source: Cloudinary-Provisioning-OAS
        publish:
            packagist:
                username: $packagist_username
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cloudinary/cloudinary/cloudinary-provisioning-php-code-samples
            blocking: true
