<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Operations;

use Cloudinary\Account\Provisioning\Utils\SpeakeasyMetadata;
class DeleteRoleRequest
{
    /**
     * A unique identifier for the role.
     *
     * @var string $roleId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=role_id')]
    public string $roleId;

    /**
     * Account ID
     *
     * @var ?string $accountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=account_id')]
    public ?string $accountId = null;

    /**
     * Determines whether the role should be deleted when it has associated principals.
     *
     * - `true`: Deletes the role even if it has associated principals.
     * - `false` (default): Prevents deletion if the role has associated principals. You must manually unassociate the principals before deleting the role.
     *
     *
     * @var ?bool $force
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=force')]
    public ?bool $force = null;

    /**
     * @param  string  $roleId
     * @param  ?string  $accountId
     * @param  ?bool  $force
     * @phpstan-pure
     */
    public function __construct(string $roleId, ?string $accountId = null, ?bool $force = null)
    {
        $this->roleId = $roleId;
        $this->accountId = $accountId;
        $this->force = $force;
    }
}