<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Operations;

use Cloudinary\Account\Provisioning\Utils\SpeakeasyMetadata;
class GetBillingUsageRequest
{
    /**
     * Account ID
     *
     * @var ?string $accountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=account_id')]
    public ?string $accountId = null;

    /**
     * The year to retrieve billing usage for. Behavior depends on subscription type (see above).
     *
     * @var ?int $year
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=year')]
    public ?int $year = null;

    /**
     * Whether to include usage details by product environment. **Default**: false.
     *
     *
     *
     * @var ?bool $includeProdenvBreakdown
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include_prodenv_breakdown')]
    public ?bool $includeProdenvBreakdown = null;

    /**
     * @param  ?string  $accountId
     * @param  ?int  $year
     * @param  ?bool  $includeProdenvBreakdown
     * @phpstan-pure
     */
    public function __construct(?string $accountId = null, ?int $year = null, ?bool $includeProdenvBreakdown = null)
    {
        $this->accountId = $accountId;
        $this->year = $year;
        $this->includeProdenvBreakdown = $includeProdenvBreakdown;
    }
}