<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Operations;

use Cloudinary\Account\Provisioning\Utils\SpeakeasyMetadata;
class GetProductEnvironmentRequest
{
    /**
     * The ID of the product environment.
     *
     * @var string $subAccountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=sub_account_id')]
    public string $subAccountId;

    /**
     * Account ID
     *
     * @var ?string $accountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=account_id')]
    public ?string $accountId = null;

    /**
     * @param  string  $subAccountId
     * @param  ?string  $accountId
     * @phpstan-pure
     */
    public function __construct(string $subAccountId, ?string $accountId = null)
    {
        $this->subAccountId = $subAccountId;
        $this->accountId = $accountId;
    }
}