<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Operations;


/** The role to assign. */
enum Role: string
{
    case MasterAdmin = 'master_admin';
    case Admin = 'admin';
    case Billing = 'billing';
    case TechnicalAdmin = 'technical_admin';
    case Reports = 'reports';
    case MediaLibraryAdmin = 'media_library_admin';
    case MediaLibraryUser = 'media_library_user';
}
