<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Operations;

use Cloudinary\Account\Provisioning\Models\Components;
use Cloudinary\Account\Provisioning\Utils\SpeakeasyMetadata;
class UpdateAccessKeyRequest
{
    /**
     * The ID of the product environment.
     *
     * @var string $subAccountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=sub_account_id')]
    public string $subAccountId;

    /**
     * The access key (api key).
     *
     * @var string $key
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=key')]
    public string $key;

    /**
     * Access key details for update.
     *
     * @var \Cloudinary\Account\Provisioning\Models\Components\AccessKeyUpdateRequest $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\AccessKeyUpdateRequest $body;

    /**
     * Account ID
     *
     * @var ?string $accountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=account_id')]
    public ?string $accountId = null;

    /**
     * @param  string  $subAccountId
     * @param  string  $key
     * @param  \Cloudinary\Account\Provisioning\Models\Components\AccessKeyUpdateRequest  $body
     * @param  ?string  $accountId
     * @phpstan-pure
     */
    public function __construct(string $subAccountId, string $key, Components\AccessKeyUpdateRequest $body, ?string $accountId = null)
    {
        $this->subAccountId = $subAccountId;
        $this->key = $key;
        $this->body = $body;
        $this->accountId = $accountId;
    }
}