<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Operations;

use Cloudinary\Account\Provisioning\Models\Components;
use Cloudinary\Account\Provisioning\Utils\SpeakeasyMetadata;
class UpdatePrincipalRolesRequest
{
    /**
     * Principal and roles details.
     *
     * @var \Cloudinary\Account\Provisioning\Models\Components\UpdatePrincipalRolesRequest $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\UpdatePrincipalRolesRequest $body;

    /**
     * Account ID
     *
     * @var ?string $accountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=account_id')]
    public ?string $accountId = null;

    /**
     * @param  \Cloudinary\Account\Provisioning\Models\Components\UpdatePrincipalRolesRequest  $body
     * @param  ?string  $accountId
     * @phpstan-pure
     */
    public function __construct(Components\UpdatePrincipalRolesRequest $body, ?string $accountId = null)
    {
        $this->body = $body;
        $this->accountId = $accountId;
    }
}