<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Operations;

use Cloudinary\Account\Provisioning\Models\Components;
use Cloudinary\Account\Provisioning\Utils\SpeakeasyMetadata;
class UpdateCustomPolicyRequest
{
    /**
     * A unique identifier for the custom permission policy.
     *
     * @var string $policyId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=policy_id')]
    public string $policyId;

    /**
     * Policy details
     *
     * @var \Cloudinary\Account\Provisioning\Models\Components\UpdateCustomPolicy $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\UpdateCustomPolicy $body;

    /**
     * Account ID
     *
     * @var ?string $accountId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=account_id')]
    public ?string $accountId = null;

    /**
     * @param  string  $policyId
     * @param  \Cloudinary\Account\Provisioning\Models\Components\UpdateCustomPolicy  $body
     * @param  ?string  $accountId
     * @phpstan-pure
     */
    public function __construct(string $policyId, Components\UpdateCustomPolicy $body, ?string $accountId = null)
    {
        $this->policyId = $policyId;
        $this->body = $body;
        $this->accountId = $accountId;
    }
}