<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Utils\Retry;

abstract class RetryConfig
{
    public RetryStrategy $strategy;
}
