<?php
/**
 * ProductEnvironmentsResponseTest
 *
 * PHP version 8.1
 *
 * @package  Cloudinary\Provisioning
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloudinary Account Provisioning API
 *
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise).
 *
 * The version of the OpenAPI document: 0.0.4
 * Contact: support@cloudinary.com
 * @generated Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cloudinary\Provisioning\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProductEnvironmentsResponseTest Class Doc Comment
 *
 * @description ProductEnvironmentsResponse
 * @package     Cloudinary\Provisioning
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProductEnvironmentsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductEnvironmentsResponse"
     */
    public function testProductEnvironmentsResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subAccounts"
     */
    public function testPropertySubAccounts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
