<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


class AccessKey
{
    /**
     * The name of the access key.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The API key.
     *
     * @var ?string $apiKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('api_key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $apiKey = null;

    /**
     * The API secret.
     *
     * @var ?string $apiSecret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('api_secret')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $apiSecret = null;

    /**
     * The date when the access key was created.
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * The date when the access key was last updated.
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * Whether the access key is enabled or disabled.
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $apiKey
     * @param  ?string  $apiSecret
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @param  ?bool  $enabled
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $apiKey = null, ?string $apiSecret = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?bool $enabled = null)
    {
        $this->name = $name;
        $this->apiKey = $apiKey;
        $this->apiSecret = $apiSecret;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->enabled = $enabled;
    }
}