<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


/** ApiAccessKey - Brief details of a single API Access Key. */
class ApiAccessKey
{
    /**
     * The API key.
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     * The API secret.
     *
     * @var ?string $secret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $secret = null;

    /**
     * Whether the access key is enabled or disabled.
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * @param  ?string  $key
     * @param  ?string  $secret
     * @param  ?bool  $enabled
     * @phpstan-pure
     */
    public function __construct(?string $key = null, ?string $secret = null, ?bool $enabled = null)
    {
        $this->key = $key;
        $this->secret = $secret;
        $this->enabled = $enabled;
    }
}