<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


/** Breakdown - Usage breakdown by asset type and operation. */
class Breakdown
{
    /**
     * Storage usage for images.
     *
     * @var ?float $storageImage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('storage_image')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $storageImage = null;

    /**
     * Storage usage for videos.
     *
     * @var ?float $storageVideo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('storage_video')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $storageVideo = null;

    /**
     * Storage usage for raw files.
     *
     * @var ?float $storageRaw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('storage_raw')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $storageRaw = null;

    /**
     * Transformation usage for images.
     *
     * @var ?float $transformationsImage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transformations_image')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $transformationsImage = null;

    /**
     * Transformation usage for videos.
     *
     * @var ?float $transformationsVideo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transformations_video')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $transformationsVideo = null;

    /**
     * Bandwidth usage for images.
     *
     * @var ?float $bandwidthImage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bandwidth_image')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $bandwidthImage = null;

    /**
     * Bandwidth usage for videos.
     *
     * @var ?float $bandwidthVideo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bandwidth_video')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $bandwidthVideo = null;

    /**
     * Bandwidth usage for raw files.
     *
     * @var ?float $bandwidthRaw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bandwidth_raw')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $bandwidthRaw = null;

    /**
     * Number of times images were delivered (impressions).
     *
     * @var ?float $imageImpressions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_impressions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $imageImpressions = null;

    /**
     * Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio).
     *
     * @var ?float $videoSeconds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('video_seconds')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $videoSeconds = null;

    /**
     * @param  ?float  $storageImage
     * @param  ?float  $storageVideo
     * @param  ?float  $storageRaw
     * @param  ?float  $transformationsImage
     * @param  ?float  $transformationsVideo
     * @param  ?float  $bandwidthImage
     * @param  ?float  $bandwidthVideo
     * @param  ?float  $bandwidthRaw
     * @param  ?float  $imageImpressions
     * @param  ?float  $videoSeconds
     * @phpstan-pure
     */
    public function __construct(?float $storageImage = null, ?float $storageVideo = null, ?float $storageRaw = null, ?float $transformationsImage = null, ?float $transformationsVideo = null, ?float $bandwidthImage = null, ?float $bandwidthVideo = null, ?float $bandwidthRaw = null, ?float $imageImpressions = null, ?float $videoSeconds = null)
    {
        $this->storageImage = $storageImage;
        $this->storageVideo = $storageVideo;
        $this->storageRaw = $storageRaw;
        $this->transformationsImage = $transformationsImage;
        $this->transformationsVideo = $transformationsVideo;
        $this->bandwidthImage = $bandwidthImage;
        $this->bandwidthVideo = $bandwidthVideo;
        $this->bandwidthRaw = $bandwidthRaw;
        $this->imageImpressions = $imageImpressions;
        $this->videoSeconds = $videoSeconds;
    }
}