<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


class CedarSchemaResponse
{
    /**
     * $schema
     *
     * @var array<string, mixed> $schema
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('schema')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>')]
    public array $schema;

    /**
     * @param  array<string, mixed>  $schema
     * @phpstan-pure
     */
    public function __construct(array $schema)
    {
        $this->schema = $schema;
    }
}