<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


/** CustomAttributes - Custom attributes associated with the product environment (optional). */
class CustomAttributes
{

    public function __construct()
    {
    }
}