<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;

use Brick\DateTime\LocalDate;
class Cycles
{
    /**
     * The start date of the billing cycle.
     *
     * @var ?LocalDate $fromDay
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_day')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $fromDay = null;

    /**
     * The end date of the billing cycle.
     *
     * @var ?LocalDate $toDay
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to_day')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $toDay = null;

    /**
     * Total usage for this cycle.
     *
     * @var ?float $usage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('usage')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $usage = null;

    /**
     * Usage breakdown by asset type and operation.
     *
     * @var ?\Cloudinary\Account\Provisioning\Models\Components\Breakdown $breakdown
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('breakdown')]
    #[\Speakeasy\Serializer\Annotation\Type('\Cloudinary\Account\Provisioning\Models\Components\Breakdown|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Breakdown $breakdown = null;

    /**
     * Optional breakdown by product environment. May not be present in all responses.
     *
     * @var ?array<\Cloudinary\Account\Provisioning\Models\Components\CloudAssetTypeBreakdown> $productEnvironmentBreakdown
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_environment_breakdown')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Cloudinary\Account\Provisioning\Models\Components\CloudAssetTypeBreakdown>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $productEnvironmentBreakdown = null;

    /**
     * @param  ?LocalDate  $fromDay
     * @param  ?LocalDate  $toDay
     * @param  ?float  $usage
     * @param  ?\Cloudinary\Account\Provisioning\Models\Components\Breakdown  $breakdown
     * @param  ?array<\Cloudinary\Account\Provisioning\Models\Components\CloudAssetTypeBreakdown>  $productEnvironmentBreakdown
     * @phpstan-pure
     */
    public function __construct(?LocalDate $fromDay = null, ?LocalDate $toDay = null, ?float $usage = null, ?Breakdown $breakdown = null, ?array $productEnvironmentBreakdown = null)
    {
        $this->fromDay = $fromDay;
        $this->toDay = $toDay;
        $this->usage = $usage;
        $this->breakdown = $breakdown;
        $this->productEnvironmentBreakdown = $productEnvironmentBreakdown;
    }
}