<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


/** Specifies whether permissions apply globally or to specific content. */
enum PermissionTypeEnum: string
{
    case Global = 'global';
    case Content = 'content';
}
