<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


/** User - User details. */
class User
{
    /**
     * The user's ID.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The user's name.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The user's first name.
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     * The user's last name.
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     * The user's role.
     *
     * @var ?string $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $role = null;

    /**
     * The user's email.
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * Whether the user is pending.
     *
     * @var ?bool $pending
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pending')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $pending = null;

    /**
     * Whether the user is enabled.
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * The date when the user was created.
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * The date when the user was last updated.
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * The date when the user was last logged in.
     *
     * @var ?\DateTime $lastLogin
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_login')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $lastLogin = null;

    /**
     *
     * @var ?bool $allSubAccounts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('all_sub_accounts')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allSubAccounts = null;

    /**
     * The list of authentication providers for the user.
     *
     * @var ?array<string> $providers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $providers = null;

    /**
     * The user's email preferences.
     *
     * @var ?\Cloudinary\Account\Provisioning\Models\Components\EmailPreferences $emailPreferences
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_preferences')]
    #[\Speakeasy\Serializer\Annotation\Type('\Cloudinary\Account\Provisioning\Models\Components\EmailPreferences|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?EmailPreferences $emailPreferences = null;

    /**
     * The account ID.
     *
     * @var ?string $accountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountId = null;

    /**
     * Whether two-factor authentication is enabled.
     *
     * @var ?bool $twoFactor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('two_factor')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $twoFactor = null;

    /**
     * The user's status.
     *
     * @var ?string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * Whether the user is a root user.
     *
     * @var ?bool $root
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('root')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $root = null;

    /**
     * The user's technical role.
     *
     * @var ?string $technicalRole
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('technical_role')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $technicalRole = null;

    /**
     * The number of groups the user belongs to.
     *
     * @var ?int $groupCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('group_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $groupCount = null;

    /**
     * The number of sub-accounts the user has access to.
     *
     * @var ?int $subAccountCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sub_account_count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $subAccountCount = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $role
     * @param  ?string  $email
     * @param  ?bool  $pending
     * @param  ?bool  $enabled
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @param  ?\DateTime  $lastLogin
     * @param  ?bool  $allSubAccounts
     * @param  ?array<string>  $providers
     * @param  ?\Cloudinary\Account\Provisioning\Models\Components\EmailPreferences  $emailPreferences
     * @param  ?string  $accountId
     * @param  ?bool  $twoFactor
     * @param  ?string  $status
     * @param  ?bool  $root
     * @param  ?string  $technicalRole
     * @param  ?int  $groupCount
     * @param  ?int  $subAccountCount
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $name = null, ?string $firstName = null, ?string $lastName = null, ?string $role = null, ?string $email = null, ?bool $pending = null, ?bool $enabled = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?\DateTime $lastLogin = null, ?bool $allSubAccounts = null, ?array $providers = null, ?EmailPreferences $emailPreferences = null, ?string $accountId = null, ?bool $twoFactor = null, ?string $status = null, ?bool $root = null, ?string $technicalRole = null, ?int $groupCount = null, ?int $subAccountCount = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->role = $role;
        $this->email = $email;
        $this->pending = $pending;
        $this->enabled = $enabled;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->lastLogin = $lastLogin;
        $this->allSubAccounts = $allSubAccounts;
        $this->providers = $providers;
        $this->emailPreferences = $emailPreferences;
        $this->accountId = $accountId;
        $this->twoFactor = $twoFactor;
        $this->status = $status;
        $this->root = $root;
        $this->technicalRole = $technicalRole;
        $this->groupCount = $groupCount;
        $this->subAccountCount = $subAccountCount;
    }
}