<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Cloudinary\Account\Provisioning\Models\Components;


class UserGroupsResponse
{
    /**
     * A list of user groups.
     *
     * @var ?array<\Cloudinary\Account\Provisioning\Models\Components\UserGroup> $userGroups
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user_groups')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Cloudinary\Account\Provisioning\Models\Components\UserGroup>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $userGroups = null;

    /**
     * @param  ?array<\Cloudinary\Account\Provisioning\Models\Components\UserGroup>  $userGroups
     * @phpstan-pure
     */
    public function __construct(?array $userGroups = null)
    {
        $this->userGroups = $userGroups;
    }
}