<?php
/**
 * EnvironmentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Cloudinary\Provisioning
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloudinary Provisioning API
 *
 * Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.   Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise).
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@cloudinary.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Cloudinary\Provisioning\Test\Api;

use \Cloudinary\Provisioning\Configuration;
use \Cloudinary\Provisioning\ApiException;
use \Cloudinary\Provisioning\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EnvironmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cloudinary\Provisioning
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnvironmentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createProductEnvironment
     *
     * Create product environment.
     *
     */
    public function testCreateProductEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProductEnvironment
     *
     * Delete product environment.
     *
     */
    public function testDeleteProductEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductEnvironment
     *
     * Get product environment.
     *
     */
    public function testGetProductEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductEnvironments
     *
     * Get product environments.
     *
     */
    public function testGetProductEnvironments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProductEnvironment
     *
     * Update product environment.
     *
     */
    public function testUpdateProductEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
